apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-rpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-rpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-rpc
    spec:
      containers:
      - image: registry.gitlab.com/tezos/flextesa:01e3f596-run
        imagePullPolicy: Always
        name: tezos-rpc
        command: ["/bin/sh", "-c"]
        #args: ["OCAMLRUNPARAM=b /opt/tezos/bin/tezos-node run --config-file /etc/tezos/nodeconfig.json -vv --singleprocess"]
        args: ["ls -la /var/tezos ; find /var/tezos /tmp/hostpath_pv/ ; cp /etc/tezos/nodeconfig.json  /var/tezos/ ; find /etc/tezos ; whoami ; echo hello > /var/tezos/hello ;  OCAMLRUNPARAM=b tezos-node run --config-file /etc/tezos/nodeconfig.json"]
        ports:
        - containerPort: 8732
          name: tezos-rpc
          containerPort: 8733
          name: tezos-net
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
